<?php

declare(strict_types=1);

namespace App\PetDomain\Cat;

final class CatBreedList
{
    public static function getAll(): array
    {
        return [
            'abyssinian' => 'Абиссинская',
            'australian-mist' => 'Австралийский мист',
            'asian' => 'Азиатская (табби)',
            'american-bobtail-longhair' => 'Американский бобтейл длинношёрстный',
            'american-bobtail-shorthair' => 'Американский бобтейл короткошёрстный',
            'american-wirehair' => 'Американская жесткошёрстная',
            'american-curl-longhair' => 'Американский кёрл длинношёрстный',
            'american-curl-shorthair' => 'Американский кёрл короткошёрстный',
            'american-shorthair' => 'Американская короткошёрстная',
            'anatolian' => 'Анатолийская',
            'arabian-mau' => 'Аравийский мау',
            'balinese' => 'Балинезийская (Балинез балийская)',
            'bengali' => 'Бенгальская',
            'bombay' => 'Бомбейская',
            'brazilian-shorthair' => 'Бразильская короткошёрстная',
            'british-longhair' => 'Британская длинношёрстная',
            'british-shorthair' => 'Британская короткошёрстная',
            'burma' => 'Бурма (Бурманская)',
            'burmilla-long-haired' => 'Бурмилла длинношёрстный',
            'burmilla-shorthair' => 'Бурмилла короткошёрстный',
            'havana' => 'Гавана',
            'himalayan-cat' => 'Гималайская кошка',
            'devon-rex' => 'Девон рекс',
            'home' => 'Домашняя',
            'don-sphinx' => 'Донской сфинкс',
            'celtic' => 'Кельтская (Европейская короткошёрстная)',
            'egyptian-mau' => 'Египетская мау',
            'york-chocolate-cat' => 'Йоркская шоколадная кошка (Шоколадный Йорк)',
            'california-shining' => 'Калифорнийская сияющая',
            'kanaani' => 'Канаани (Ханаани) ',
            'karelian-bobtail-longhair' => 'Карельский бобтейл длинношёрстный',
            'karelian-bobtail-shorthair' => 'Карельский бобтейл короткошёрстный',
            'kimrick' => 'Кимрик',
            'korat' => 'Корат',
            'cornish-rex' => 'Корниш рекс',
            'kuril-bobtail-longhair' => 'Курильский бобтейл длинношёрстный',
            'kuril-bobtail-shorthair' => 'Курильский бобтейл короткошёрстный',
            'laperm-longhair' => 'Лаперм длинношёрстный',
            'laperm-shorthair' => 'Лаперм короткошёрстный',
            'munchkin-longhair' => 'Манчкин длинношёрстная',
            'munchkin-shorthair' => 'Манчкин короткошёрстная',
            'maine-coon' => 'Мейн-кун',
            'mekong-bobtail' => 'Меконгский бобтейл',
            'minskin' => 'Минскин',
            'manx' => 'Мэнкс (Мэнская кошка)',
            'napoleon' => 'Наполеон',
            'german-rex' => 'Немецкий рекс',
            'nibelung' => 'Нибелунг',
            'norwegian-forest' => 'Норвежская лесная',
            'oregon-rex' => 'Орегон-рекс',
            'oriental-longhair' => 'Ориентальная длинношёрстная',
            'oriental-shorthair' => 'Ориентальная короткошёрстная',
            'ojos-azules' => 'Охос азулес',
            'ojos-azules-longhair' => 'Охос азулес длинношёрстный',
            'ocicat' => 'Оцикет',
            'persian' => 'Персидская (Колорпойнт)',
            'colorpoint' => 'Колорпойнт',
            'peterbald' => 'Петерболд',
            'pixibob-long-haired' => 'Пиксибоб длинношёрстный',
            'pixibob-shorthair' => 'Пиксибоб короткошёрстный',
            'ragamuffin' => 'Рагамаффин',
            'russian-blue' => 'Русская голубая',
            'ragdoll' => 'Рэгдолл',
            'savannah' => 'Саванна',
            'sacred-burmese' => 'Священная бирманская',
            'seychelles-longhair' => 'Сейшельская длинношёрстная',
            'seychelles-shorthair' => 'Сейшельская короткошёрстная',
            'selkirk-rex-longhair' => 'Селкирк рекс длинношёрстный',
            'selkirk-rex-shorthair' => 'Селкирк рекс короткошёрстный',
            'serengeti' => 'Серенгети',
            'siamese' => 'Сиамская',
            'siberian' => 'Сибирская',
            'neva-masquerade' => 'Невская маскарадная',
            'singaporean' => 'Сингапурская',
            'scottish-fold' => 'Скоттиш фолд',
            'scottish-straight-cat-' => 'Шотландская прямоухая кошка (cкоттиш страйт)',
            'snow-shu' => 'Сноу-Шу',
            'sokoke' => 'Сококе (Соукок)',
            'somalia' => 'Сомали (Сомалийская кошка)',
            'canadian-sphinx' => 'Канадский сфинкс',
            'thai' => 'Тайская',
            'chantilly-tiffans' => 'Шантильи Тиффаны',
            'toyger' => 'Тойгер',
            'tonkinesis-' => 'Тонкинез (Тонкинская кошка)',
            'turkish-angora' => 'Турецкая ангора',
            'turkish-van' => 'Турецкий ван',
            'ukrainian-levkoy' => 'Украинский левкой',
            'ural-rex-longhair' => 'Уральский рекс длинношёрстный',
            'ural-rex-shorthair' => 'Уральский рекс короткошёрстный',
            'forin-white' => 'Форин Вайт',
            'scottish-fold-longhair-' => 'Хайленд фолд (Шотландская вислоухая длинношерстная кошка)',
            'cat-of-sri-lanka-' => 'Цейлонская (кошка Шри-Ланки)',
            'chausie' => 'Чаузи',
            'chartreuse' => 'Шартрез (Картезианская кошка)',
            'chinchilla' => 'Шиншилла',
            'aegean' => 'Эгейская',
            'exot' => 'Экзот (Экзотическая короткошерстная кошка)',
            'javanese-' => 'Яванез (Яванская кошка)',
            'japanese-bobtail-longhair' => 'Японский бобтейл длинношёрстный',
            'japanese-bobtail-shorthair' => 'Японский бобтейл короткошёрстный',
        ];
    }
}
