version: "3.3"

services:
  database:
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    build:
      context: docker/database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Europe/London'
      PGTZ: 'Europe/London'

  php:
    image: 641201314091.dkr.ecr.eu-central-1.amazonaws.com/api-php-dev:${PROJECT_VERSION:-latest}
    depends_on:
      - database
    user: "1000:1000"
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME:-lookpet.docker}
      XDEBUG_CONFIG: remote_host=${XDEBUG_HOST:-192.168.99.1}
    volumes:
      - ${PROJECT_DIR_LOCATION_HOST}:/app

  nginx:
    image: 641201314091.dkr.ecr.eu-central-1.amazonaws.com/nginx:${PROJECT_VERSION:-latest}
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_PUBLIC_DIR_LOCATION_HOST}:/app/public