version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make aws-v1-login
      - run: make build-dev-all
      - run: make fix-cs
      - run: make build-push
      - run: make deploy-prod